services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: # <-- THIS IS THE FIX
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"